name: RhttpCurlLogger

repository: https://github.com/albinpk/rhttp_curl_logger

packages:
  - packages/*

sdkPath: packages/rhttp_curl_logger/.fvm/flutter_sdk

command:
  version:
    hooks:
      # Update the version in readme
      preCommit: bash -c "$(curl -s https://raw.githubusercontent.com/albinpk/flutter_cora/refs/heads/dev/scripts/preVersion.sh)"
