name: rhttp_curl_logger
description: "A new Flutter package project."

version: 0.0.0
# homepage:

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^8.0.0
