name: deploy

on:
  push:
    tags:
      - "rhttp_curl_logger-v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    uses: albinpk/actions/.github/workflows/pub_deploy.yml@v1.2.1
    secrets: inherit
    with:
      working-directory: packages/rhttp_curl_logger
